//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.9.0
//     from Assets/Script/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @InputMaster: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""d8df879c-b141-4ca3-9870-545ba00d63a6"",
            ""actions"": [
                {
                    ""name"": ""movement"",
                    ""type"": ""Value"",
                    ""id"": ""c5b69fa4-f096-472d-adcb-67393f408c49"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ba821234-142a-4720-8d96-db286b40b4df"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""faf3f913-9732-439f-aea6-9147e1d775d5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookPress"",
                    ""type"": ""Button"",
                    ""id"": ""5c4e2c04-ba87-4915-b55a-0dad04de8227"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""ab3af3a1-e6ab-4117-a551-d1ee0bee5d08"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Clamp(min=-0.1,max=0.1),Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""0ee96900-5122-4d5e-8528-0c8cab7fd8f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""ded4f3e2-1d53-4e26-b524-65c7ed7f7436"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""73659c70-fb28-4faa-87f2-88ae4253a8c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Base_Attack"",
                    ""type"": ""Button"",
                    ""id"": ""17b98521-3b68-4c9b-b462-6910e88f139d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charged_Attack"",
                    ""type"": ""Button"",
                    ""id"": ""edd8961a-1371-43f0-b7b9-75fddee2057f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.75)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnlockCursor"",
                    ""type"": ""Button"",
                    ""id"": ""816c1d89-a43f-4a71-8c07-d751fa1b3a77"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharater1"",
                    ""type"": ""Button"",
                    ""id"": ""bea34cb8-d126-4d18-8abb-5f41edaef521"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharater2"",
                    ""type"": ""Button"",
                    ""id"": ""20869042-0960-4189-af52-a1a3bd2a3618"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharater3"",
                    ""type"": ""Button"",
                    ""id"": ""07f53f87-2f16-4694-81c1-cf7fc2529034"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharater4"",
                    ""type"": ""Button"",
                    ""id"": ""d033020c-7131-4c81-9b0c-bf9b34ef81ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDebug"",
                    ""type"": ""Button"",
                    ""id"": ""cf49509d-b9b8-46dd-b5a6-919891fc6676"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""3ec38554-ad95-4fff-994e-fee71e001511"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""697988ef-4f6a-4edd-a2b8-9aa611d1a83b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""136b79fe-6ace-4b88-aa0f-40e62bfbdc6e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Phone"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""245207a6-c25f-4776-a984-895e1f029e5b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""19644c22-7794-4735-b8fb-25c31d45f077"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""31b14836-e87a-4239-973f-8389a640771e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a6e1f1c4-3e9f-4920-a9f4-cf1a2585cd1b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d7510905-e701-4bf5-93a4-848bacf92a4d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4cf4c3e1-8f26-4d7a-b5e9-849ac586b95b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Phone;Gamepad"",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1641e6a2-cadf-406a-a44b-0c5a732538a9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8884d658-e5ea-40f0-a947-32ff59311e50"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Phone;Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a760ca8-3115-4bb3-8e9f-eb416a53f58c"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""LookPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a1a3d09-6455-45e9-ab29-0bc9a6af6b8a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Clamp(min=-4,max=4)"",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Player Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f31a46d8-45df-4f13-ba45-098704098cbd"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba190b5a-45f4-4b14-a64b-dd891e0e17b1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15576076-294f-4160-8cf3-18e21d1ef73f"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Walk Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fac22640-39d2-455e-99ba-be62fd7f7144"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bb82fbd-29af-49a6-9f28-c9cc7c84405a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f6147b6-5d50-4a80-ad27-987034d238ea"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Base_Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88a02f32-e5cd-42d6-b66b-2a6cda747977"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Charged_Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bc82360-9b88-4527-93f4-04cae4c0cbfc"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""UnlockCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c9a11b-d98d-43b8-979d-9c3146d12586"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""SwitchCharater1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""582e9c25-f3ec-43ae-b635-e1687882aadf"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""SwitchCharater2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f731f524-52df-4679-9ba7-c7ac577ad5df"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharater3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e51e4a87-1120-4259-a038-d26681165d52"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharater4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69fb53c5-f7a3-40dd-8038-c76a40e8bd50"",
                    ""path"": ""<Keyboard>/f10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDebug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdc89f7a-2125-4ede-9174-4db87f40f5e9"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DebugAction"",
            ""id"": ""aff778b1-4af6-478e-95e4-d1dbf9c60c49"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Phone"",
            ""bindingGroup"": ""Phone"",
            ""devices"": [
                {
                    ""devicePath"": ""<AndroidGamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<iOSGameController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // player
        m_player = asset.FindActionMap("player", throwIfNotFound: true);
        m_player_movement = m_player.FindAction("movement", throwIfNotFound: true);
        m_player_Jump = m_player.FindAction("Jump", throwIfNotFound: true);
        m_player_Look = m_player.FindAction("Look", throwIfNotFound: true);
        m_player_LookPress = m_player.FindAction("LookPress", throwIfNotFound: true);
        m_player_PlayerZoom = m_player.FindAction("Player Zoom", throwIfNotFound: true);
        m_player_Sprint = m_player.FindAction("Sprint", throwIfNotFound: true);
        m_player_Dash = m_player.FindAction("Dash", throwIfNotFound: true);
        m_player_WalkToggle = m_player.FindAction("Walk Toggle", throwIfNotFound: true);
        m_player_Base_Attack = m_player.FindAction("Base_Attack", throwIfNotFound: true);
        m_player_Charged_Attack = m_player.FindAction("Charged_Attack", throwIfNotFound: true);
        m_player_UnlockCursor = m_player.FindAction("UnlockCursor", throwIfNotFound: true);
        m_player_SwitchCharater1 = m_player.FindAction("SwitchCharater1", throwIfNotFound: true);
        m_player_SwitchCharater2 = m_player.FindAction("SwitchCharater2", throwIfNotFound: true);
        m_player_SwitchCharater3 = m_player.FindAction("SwitchCharater3", throwIfNotFound: true);
        m_player_SwitchCharater4 = m_player.FindAction("SwitchCharater4", throwIfNotFound: true);
        m_player_ToggleDebug = m_player.FindAction("ToggleDebug", throwIfNotFound: true);
        m_player_Return = m_player.FindAction("Return", throwIfNotFound: true);
        // DebugAction
        m_DebugAction = asset.FindActionMap("DebugAction", throwIfNotFound: true);
    }

    ~@InputMaster()
    {
        Debug.Assert(!m_player.enabled, "This will cause a leak and performance issues, InputMaster.player.Disable() has not been called.");
        Debug.Assert(!m_DebugAction.enabled, "This will cause a leak and performance issues, InputMaster.DebugAction.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player
    private readonly InputActionMap m_player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_player_movement;
    private readonly InputAction m_player_Jump;
    private readonly InputAction m_player_Look;
    private readonly InputAction m_player_LookPress;
    private readonly InputAction m_player_PlayerZoom;
    private readonly InputAction m_player_Sprint;
    private readonly InputAction m_player_Dash;
    private readonly InputAction m_player_WalkToggle;
    private readonly InputAction m_player_Base_Attack;
    private readonly InputAction m_player_Charged_Attack;
    private readonly InputAction m_player_UnlockCursor;
    private readonly InputAction m_player_SwitchCharater1;
    private readonly InputAction m_player_SwitchCharater2;
    private readonly InputAction m_player_SwitchCharater3;
    private readonly InputAction m_player_SwitchCharater4;
    private readonly InputAction m_player_ToggleDebug;
    private readonly InputAction m_player_Return;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @movement => m_Wrapper.m_player_movement;
        public InputAction @Jump => m_Wrapper.m_player_Jump;
        public InputAction @Look => m_Wrapper.m_player_Look;
        public InputAction @LookPress => m_Wrapper.m_player_LookPress;
        public InputAction @PlayerZoom => m_Wrapper.m_player_PlayerZoom;
        public InputAction @Sprint => m_Wrapper.m_player_Sprint;
        public InputAction @Dash => m_Wrapper.m_player_Dash;
        public InputAction @WalkToggle => m_Wrapper.m_player_WalkToggle;
        public InputAction @Base_Attack => m_Wrapper.m_player_Base_Attack;
        public InputAction @Charged_Attack => m_Wrapper.m_player_Charged_Attack;
        public InputAction @UnlockCursor => m_Wrapper.m_player_UnlockCursor;
        public InputAction @SwitchCharater1 => m_Wrapper.m_player_SwitchCharater1;
        public InputAction @SwitchCharater2 => m_Wrapper.m_player_SwitchCharater2;
        public InputAction @SwitchCharater3 => m_Wrapper.m_player_SwitchCharater3;
        public InputAction @SwitchCharater4 => m_Wrapper.m_player_SwitchCharater4;
        public InputAction @ToggleDebug => m_Wrapper.m_player_ToggleDebug;
        public InputAction @Return => m_Wrapper.m_player_Return;
        public InputActionMap Get() { return m_Wrapper.m_player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @movement.started += instance.OnMovement;
            @movement.performed += instance.OnMovement;
            @movement.canceled += instance.OnMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @LookPress.started += instance.OnLookPress;
            @LookPress.performed += instance.OnLookPress;
            @LookPress.canceled += instance.OnLookPress;
            @PlayerZoom.started += instance.OnPlayerZoom;
            @PlayerZoom.performed += instance.OnPlayerZoom;
            @PlayerZoom.canceled += instance.OnPlayerZoom;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @WalkToggle.started += instance.OnWalkToggle;
            @WalkToggle.performed += instance.OnWalkToggle;
            @WalkToggle.canceled += instance.OnWalkToggle;
            @Base_Attack.started += instance.OnBase_Attack;
            @Base_Attack.performed += instance.OnBase_Attack;
            @Base_Attack.canceled += instance.OnBase_Attack;
            @Charged_Attack.started += instance.OnCharged_Attack;
            @Charged_Attack.performed += instance.OnCharged_Attack;
            @Charged_Attack.canceled += instance.OnCharged_Attack;
            @UnlockCursor.started += instance.OnUnlockCursor;
            @UnlockCursor.performed += instance.OnUnlockCursor;
            @UnlockCursor.canceled += instance.OnUnlockCursor;
            @SwitchCharater1.started += instance.OnSwitchCharater1;
            @SwitchCharater1.performed += instance.OnSwitchCharater1;
            @SwitchCharater1.canceled += instance.OnSwitchCharater1;
            @SwitchCharater2.started += instance.OnSwitchCharater2;
            @SwitchCharater2.performed += instance.OnSwitchCharater2;
            @SwitchCharater2.canceled += instance.OnSwitchCharater2;
            @SwitchCharater3.started += instance.OnSwitchCharater3;
            @SwitchCharater3.performed += instance.OnSwitchCharater3;
            @SwitchCharater3.canceled += instance.OnSwitchCharater3;
            @SwitchCharater4.started += instance.OnSwitchCharater4;
            @SwitchCharater4.performed += instance.OnSwitchCharater4;
            @SwitchCharater4.canceled += instance.OnSwitchCharater4;
            @ToggleDebug.started += instance.OnToggleDebug;
            @ToggleDebug.performed += instance.OnToggleDebug;
            @ToggleDebug.canceled += instance.OnToggleDebug;
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @movement.started -= instance.OnMovement;
            @movement.performed -= instance.OnMovement;
            @movement.canceled -= instance.OnMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @LookPress.started -= instance.OnLookPress;
            @LookPress.performed -= instance.OnLookPress;
            @LookPress.canceled -= instance.OnLookPress;
            @PlayerZoom.started -= instance.OnPlayerZoom;
            @PlayerZoom.performed -= instance.OnPlayerZoom;
            @PlayerZoom.canceled -= instance.OnPlayerZoom;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @WalkToggle.started -= instance.OnWalkToggle;
            @WalkToggle.performed -= instance.OnWalkToggle;
            @WalkToggle.canceled -= instance.OnWalkToggle;
            @Base_Attack.started -= instance.OnBase_Attack;
            @Base_Attack.performed -= instance.OnBase_Attack;
            @Base_Attack.canceled -= instance.OnBase_Attack;
            @Charged_Attack.started -= instance.OnCharged_Attack;
            @Charged_Attack.performed -= instance.OnCharged_Attack;
            @Charged_Attack.canceled -= instance.OnCharged_Attack;
            @UnlockCursor.started -= instance.OnUnlockCursor;
            @UnlockCursor.performed -= instance.OnUnlockCursor;
            @UnlockCursor.canceled -= instance.OnUnlockCursor;
            @SwitchCharater1.started -= instance.OnSwitchCharater1;
            @SwitchCharater1.performed -= instance.OnSwitchCharater1;
            @SwitchCharater1.canceled -= instance.OnSwitchCharater1;
            @SwitchCharater2.started -= instance.OnSwitchCharater2;
            @SwitchCharater2.performed -= instance.OnSwitchCharater2;
            @SwitchCharater2.canceled -= instance.OnSwitchCharater2;
            @SwitchCharater3.started -= instance.OnSwitchCharater3;
            @SwitchCharater3.performed -= instance.OnSwitchCharater3;
            @SwitchCharater3.canceled -= instance.OnSwitchCharater3;
            @SwitchCharater4.started -= instance.OnSwitchCharater4;
            @SwitchCharater4.performed -= instance.OnSwitchCharater4;
            @SwitchCharater4.canceled -= instance.OnSwitchCharater4;
            @ToggleDebug.started -= instance.OnToggleDebug;
            @ToggleDebug.performed -= instance.OnToggleDebug;
            @ToggleDebug.canceled -= instance.OnToggleDebug;
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @player => new PlayerActions(this);

    // DebugAction
    private readonly InputActionMap m_DebugAction;
    private List<IDebugActionActions> m_DebugActionActionsCallbackInterfaces = new List<IDebugActionActions>();
    public struct DebugActionActions
    {
        private @InputMaster m_Wrapper;
        public DebugActionActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_DebugAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActionActions set) { return set.Get(); }
        public void AddCallbacks(IDebugActionActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IDebugActionActions instance)
        {
        }

        public void RemoveCallbacks(IDebugActionActions instance)
        {
            if (m_Wrapper.m_DebugActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugActionActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugActionActions @DebugAction => new DebugActionActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    private int m_PhoneSchemeIndex = -1;
    public InputControlScheme PhoneScheme
    {
        get
        {
            if (m_PhoneSchemeIndex == -1) m_PhoneSchemeIndex = asset.FindControlSchemeIndex("Phone");
            return asset.controlSchemes[m_PhoneSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnLookPress(InputAction.CallbackContext context);
        void OnPlayerZoom(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnWalkToggle(InputAction.CallbackContext context);
        void OnBase_Attack(InputAction.CallbackContext context);
        void OnCharged_Attack(InputAction.CallbackContext context);
        void OnUnlockCursor(InputAction.CallbackContext context);
        void OnSwitchCharater1(InputAction.CallbackContext context);
        void OnSwitchCharater2(InputAction.CallbackContext context);
        void OnSwitchCharater3(InputAction.CallbackContext context);
        void OnSwitchCharater4(InputAction.CallbackContext context);
        void OnToggleDebug(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
    }
    public interface IDebugActionActions
    {
    }
}
